Remove pyproject.toml for pip config, as it caused errors
pyproject.toml was copied from the Django docs, but caused an error:
ERROR: No matching distribution found for setuptools>=40.8.0